version: 1.0.{build}

skip_tags: true

environment:
  release_notes: initial
  
build_script:
- cmd: set release_notes=build
- 7z a node-test.zip C:\avvm\node\6.11.0\x86\*

before_deploy:
- cmd: set release_notes=before deploy

artifacts:
- path: readme.md
- path: node-test.zip

test: off

deploy:
- provider: GitHub
  description: $(release_notes)
  auth_token:
    secure: yAEZVaCdcSOpENGadaHzslwH6e2HANys6hZyoJHUucLvWc/9tn06YyunMVJzsXzL
