version: 1.0.{build}

skip_tags: true

environment:
  release_notes: initial
  
build_script:
- cmd: set release_notes=build

before_deploy:
- cmd: set release_notes=before deploy

artifacts:
- path: readme.md

test: off

deploy:
- provider: GitHub
  description: $(release_notes)
  auth_token:
    secure: SmG+Y+vEaSwXtM3myFqY6UeVTV4AUSN0hzh9aEsgEJSRKpt6P+JtMPzqhl0DKngS
